### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by dengdai68** [a616567126/GPT-WEB-CLIENT#6]
nodejs v19.8.1

npm WARN old lockfile HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@vue%2fvue-loader-v15 - Not found
npm WARN old lockfile     at /opt/homebrew/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:734:24)
npm WARN old lockfile  Could not fetch metadata for @vue/vue-loader-v15@15.10.1 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@vue%2fvue-loader-v15 - Not found
npm WARN old lockfile     at /opt/homebrew/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:734:24) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     date: [ 'Sat, 29 Apr 2023 12:07:22 GMT' ],
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '21' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     vary: [ 'Accept-Encoding' ],
npm WARN old lockfile     server: [ 'cloudflare' ],
npm WARN old lockfile     'cf-ray': [ '7bf76c9a1da41018-LAX' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 404,
npm WARN old lockfile   code: 'E404',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://registry.npmjs.org/@vue%2fvue-loader-v15',
npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: '@vue/vue-loader-v15@15.10.1'
npm WARN old lockfile }
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: chat_gpt@0.1.0
npm ERR! Found: vue@2.7.14
npm ERR! node_modules/vue
npm ERR!   vue@"^2.6.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.x" from vue-codemirror@6.1.1
npm ERR! node_modules/vue-codemirror
npm ERR!   vue-codemirror@"^6.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

这是为啥

**Comment by a616567126** [comment]
尝试使用14node 16 npm试试

dengdai68 ***@***.***> 于2023年4月29日周六 20:12写道：
